// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow/core/protobuf/eager_service.proto

package tensorflow_eager

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	framework "github.com/tensorflow/tensorflow/tensorflow/go/core/framework"
	protobuf "github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RemoteTensorHandle struct {
	// The ID of the operation that produced this tensor.
	OpId int64 `protobuf:"varint,1,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	// The index into the outputs of the operation that produced this tensor.
	OutputNum            int32    `protobuf:"varint,2,opt,name=output_num,json=outputNum,proto3" json:"output_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoteTensorHandle) Reset()         { *m = RemoteTensorHandle{} }
func (m *RemoteTensorHandle) String() string { return proto.CompactTextString(m) }
func (*RemoteTensorHandle) ProtoMessage()    {}
func (*RemoteTensorHandle) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f63cfa0a7bc4510, []int{0}
}

func (m *RemoteTensorHandle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoteTensorHandle.Unmarshal(m, b)
}
func (m *RemoteTensorHandle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoteTensorHandle.Marshal(b, m, deterministic)
}
func (m *RemoteTensorHandle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteTensorHandle.Merge(m, src)
}
func (m *RemoteTensorHandle) XXX_Size() int {
	return xxx_messageInfo_RemoteTensorHandle.Size(m)
}
func (m *RemoteTensorHandle) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteTensorHandle.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteTensorHandle proto.InternalMessageInfo

func (m *RemoteTensorHandle) GetOpId() int64 {
	if m != nil {
		return m.OpId
	}
	return 0
}

func (m *RemoteTensorHandle) GetOutputNum() int32 {
	if m != nil {
		return m.OutputNum
	}
	return 0
}

// A proto representation of an eager operation.
type Operation struct {
	// A unique identifier for the operation. Set by the client so that the client
	// can uniquely identify the outputs of the scheduled operation.
	//
	// In the initial implementation, sending duplicate IDs has undefined
	// behaviour, but additional constraints may be placed upon this in the
	// future.
	Id     int64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Inputs []*RemoteTensorHandle `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty"`
	// Control Operation IDs that will be respected when ops are re-ordered by
	// async execution. If async execution (+ op re-ordering) is not enabled, this
	// should have no effect.
	ControlOpIds         []int64                         `protobuf:"varint,4,rep,packed,name=control_op_ids,json=controlOpIds,proto3" json:"control_op_ids,omitempty"`
	Attrs                map[string]*framework.AttrValue `protobuf:"bytes,5,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Device               string                          `protobuf:"bytes,6,opt,name=device,proto3" json:"device,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f63cfa0a7bc4510, []int{1}
}

func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (m *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(m, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Operation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Operation) GetInputs() []*RemoteTensorHandle {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *Operation) GetControlOpIds() []int64 {
	if m != nil {
		return m.ControlOpIds
	}
	return nil
}

func (m *Operation) GetAttrs() map[string]*framework.AttrValue {
	if m != nil {
		return m.Attrs
	}
	return nil
}

func (m *Operation) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

type QueueItem struct {
	// The remote executor should be able to handle either executing ops directly,
	// or releasing any unused tensor handles, since the tensor lifetime is
	// maintained by the client.
	//
	// Types that are valid to be assigned to Item:
	//	*QueueItem_HandleToDecref
	//	*QueueItem_Operation
	Item                 isQueueItem_Item `protobuf_oneof:"item"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *QueueItem) Reset()         { *m = QueueItem{} }
func (m *QueueItem) String() string { return proto.CompactTextString(m) }
func (*QueueItem) ProtoMessage()    {}
func (*QueueItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f63cfa0a7bc4510, []int{2}
}

func (m *QueueItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueItem.Unmarshal(m, b)
}
func (m *QueueItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueItem.Marshal(b, m, deterministic)
}
func (m *QueueItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueItem.Merge(m, src)
}
func (m *QueueItem) XXX_Size() int {
	return xxx_messageInfo_QueueItem.Size(m)
}
func (m *QueueItem) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueItem.DiscardUnknown(m)
}

var xxx_messageInfo_QueueItem proto.InternalMessageInfo

type isQueueItem_Item interface {
	isQueueItem_Item()
}

type QueueItem_HandleToDecref struct {
	HandleToDecref *RemoteTensorHandle `protobuf:"bytes,1,opt,name=handle_to_decref,json=handleToDecref,proto3,oneof"`
}

type QueueItem_Operation struct {
	Operation *Operation `protobuf:"bytes,2,opt,name=operation,proto3,oneof"`
}

func (*QueueItem_HandleToDecref) isQueueItem_Item() {}

func (*QueueItem_Operation) isQueueItem_Item() {}

func (m *QueueItem) GetItem() isQueueItem_Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *QueueItem) GetHandleToDecref() *RemoteTensorHandle {
	if x, ok := m.GetItem().(*QueueItem_HandleToDecref); ok {
		return x.HandleToDecref
	}
	return nil
}

func (m *QueueItem) GetOperation() *Operation {
	if x, ok := m.GetItem().(*QueueItem_Operation); ok {
		return x.Operation
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*QueueItem) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*QueueItem_HandleToDecref)(nil),
		(*QueueItem_Operation)(nil),
	}
}

type QueueResponse struct {
	Shape                []*framework.TensorShapeProto `protobuf:"bytes,1,rep,name=shape,proto3" json:"shape,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *QueueResponse) Reset()         { *m = QueueResponse{} }
func (m *QueueResponse) String() string { return proto.CompactTextString(m) }
func (*QueueResponse) ProtoMessage()    {}
func (*QueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f63cfa0a7bc4510, []int{3}
}

func (m *QueueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueResponse.Unmarshal(m, b)
}
func (m *QueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueResponse.Marshal(b, m, deterministic)
}
func (m *QueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueResponse.Merge(m, src)
}
func (m *QueueResponse) XXX_Size() int {
	return xxx_messageInfo_QueueResponse.Size(m)
}
func (m *QueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueueResponse proto.InternalMessageInfo

func (m *QueueResponse) GetShape() []*framework.TensorShapeProto {
	if m != nil {
		return m.Shape
	}
	return nil
}

type CreateContextRequest struct {
	// Identifies the full cluster, and this particular worker's position within.
	ServerDef *protobuf.ServerDef `protobuf:"bytes,1,opt,name=server_def,json=serverDef,proto3" json:"server_def,omitempty"`
	// Whether the ops on the worker should be executed synchronously or
	// asynchronously. By default, ops are executed synchronously.
	Async bool `protobuf:"varint,2,opt,name=async,proto3" json:"async,omitempty"`
	// Number of seconds to keep the context alive. If more than keep_alive_secs
	// has passed since a particular context has been communicated with, it will
	// be garbage collected.
	KeepAliveSecs int64 `protobuf:"varint,3,opt,name=keep_alive_secs,json=keepAliveSecs,proto3" json:"keep_alive_secs,omitempty"`
	// This is the version for all the ops that will be enqueued by the client.
	VersionDef *framework.VersionDef `protobuf:"bytes,4,opt,name=version_def,json=versionDef,proto3" json:"version_def,omitempty"`
	// Device attributes in the cluster
	ClusterDeviceAttributes []*framework.DeviceAttributes `protobuf:"bytes,6,rep,name=cluster_device_attributes,json=clusterDeviceAttributes,proto3" json:"cluster_device_attributes,omitempty"`
	// The ID of the created context. This is usually a randomly generated number,
	// that will be used to identify the context in future requests to the
	// service. Contexts are not persisted through server restarts.
	// This ID will be used for all future communications as well. It is essential
	// that both ends use this ID for selecting a rendezvous to get everything to
	// match.
	ContextId            uint64   `protobuf:"fixed64,7,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateContextRequest) Reset()         { *m = CreateContextRequest{} }
func (m *CreateContextRequest) String() string { return proto.CompactTextString(m) }
func (*CreateContextRequest) ProtoMessage()    {}
func (*CreateContextRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f63cfa0a7bc4510, []int{4}
}

func (m *CreateContextRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContextRequest.Unmarshal(m, b)
}
func (m *CreateContextRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContextRequest.Marshal(b, m, deterministic)
}
func (m *CreateContextRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContextRequest.Merge(m, src)
}
func (m *CreateContextRequest) XXX_Size() int {
	return xxx_messageInfo_CreateContextRequest.Size(m)
}
func (m *CreateContextRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContextRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContextRequest proto.InternalMessageInfo

func (m *CreateContextRequest) GetServerDef() *protobuf.ServerDef {
	if m != nil {
		return m.ServerDef
	}
	return nil
}

func (m *CreateContextRequest) GetAsync() bool {
	if m != nil {
		return m.Async
	}
	return false
}

func (m *CreateContextRequest) GetKeepAliveSecs() int64 {
	if m != nil {
		return m.KeepAliveSecs
	}
	return 0
}

func (m *CreateContextRequest) GetVersionDef() *framework.VersionDef {
	if m != nil {
		return m.VersionDef
	}
	return nil
}

func (m *CreateContextRequest) GetClusterDeviceAttributes() []*framework.DeviceAttributes {
	if m != nil {
		return m.ClusterDeviceAttributes
	}
	return nil
}

func (m *CreateContextRequest) GetContextId() uint64 {
	if m != nil {
		return m.ContextId
	}
	return 0
}

type CreateContextResponse struct {
	// List of devices that are locally accessible to the worker.
	DeviceAttributes     []*framework.DeviceAttributes `protobuf:"bytes,2,rep,name=device_attributes,json=deviceAttributes,proto3" json:"device_attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *CreateContextResponse) Reset()         { *m = CreateContextResponse{} }
func (m *CreateContextResponse) String() string { return proto.CompactTextString(m) }
func (*CreateContextResponse) ProtoMessage()    {}
func (*CreateContextResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f63cfa0a7bc4510, []int{5}
}

func (m *CreateContextResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContextResponse.Unmarshal(m, b)
}
func (m *CreateContextResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContextResponse.Marshal(b, m, deterministic)
}
func (m *CreateContextResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContextResponse.Merge(m, src)
}
func (m *CreateContextResponse) XXX_Size() int {
	return xxx_messageInfo_CreateContextResponse.Size(m)
}
func (m *CreateContextResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContextResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContextResponse proto.InternalMessageInfo

func (m *CreateContextResponse) GetDeviceAttributes() []*framework.DeviceAttributes {
	if m != nil {
		return m.DeviceAttributes
	}
	return nil
}

type EnqueueRequest struct {
	ContextId            uint64       `protobuf:"fixed64,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	Queue                []*QueueItem `protobuf:"bytes,3,rep,name=queue,proto3" json:"queue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EnqueueRequest) Reset()         { *m = EnqueueRequest{} }
func (m *EnqueueRequest) String() string { return proto.CompactTextString(m) }
func (*EnqueueRequest) ProtoMessage()    {}
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f63cfa0a7bc4510, []int{6}
}

func (m *EnqueueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnqueueRequest.Unmarshal(m, b)
}
func (m *EnqueueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnqueueRequest.Marshal(b, m, deterministic)
}
func (m *EnqueueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnqueueRequest.Merge(m, src)
}
func (m *EnqueueRequest) XXX_Size() int {
	return xxx_messageInfo_EnqueueRequest.Size(m)
}
func (m *EnqueueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnqueueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnqueueRequest proto.InternalMessageInfo

func (m *EnqueueRequest) GetContextId() uint64 {
	if m != nil {
		return m.ContextId
	}
	return 0
}

func (m *EnqueueRequest) GetQueue() []*QueueItem {
	if m != nil {
		return m.Queue
	}
	return nil
}

type EnqueueResponse struct {
	// A single operation response for every item in the request.
	QueueResponse        []*QueueResponse `protobuf:"bytes,1,rep,name=queue_response,json=queueResponse,proto3" json:"queue_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *EnqueueResponse) Reset()         { *m = EnqueueResponse{} }
func (m *EnqueueResponse) String() string { return proto.CompactTextString(m) }
func (*EnqueueResponse) ProtoMessage()    {}
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f63cfa0a7bc4510, []int{7}
}

func (m *EnqueueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnqueueResponse.Unmarshal(m, b)
}
func (m *EnqueueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnqueueResponse.Marshal(b, m, deterministic)
}
func (m *EnqueueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnqueueResponse.Merge(m, src)
}
func (m *EnqueueResponse) XXX_Size() int {
	return xxx_messageInfo_EnqueueResponse.Size(m)
}
func (m *EnqueueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnqueueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnqueueResponse proto.InternalMessageInfo

func (m *EnqueueResponse) GetQueueResponse() []*QueueResponse {
	if m != nil {
		return m.QueueResponse
	}
	return nil
}

type WaitQueueDoneRequest struct {
	ContextId uint64 `protobuf:"fixed64,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	// Ids to wait on. If empty, wait on everything currently pending.
	OpId                 []int64  `protobuf:"varint,2,rep,packed,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WaitQueueDoneRequest) Reset()         { *m = WaitQueueDoneRequest{} }
func (m *WaitQueueDoneRequest) String() string { return proto.CompactTextString(m) }
func (*WaitQueueDoneRequest) ProtoMessage()    {}
func (*WaitQueueDoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f63cfa0a7bc4510, []int{8}
}

func (m *WaitQueueDoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaitQueueDoneRequest.Unmarshal(m, b)
}
func (m *WaitQueueDoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaitQueueDoneRequest.Marshal(b, m, deterministic)
}
func (m *WaitQueueDoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaitQueueDoneRequest.Merge(m, src)
}
func (m *WaitQueueDoneRequest) XXX_Size() int {
	return xxx_messageInfo_WaitQueueDoneRequest.Size(m)
}
func (m *WaitQueueDoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WaitQueueDoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WaitQueueDoneRequest proto.InternalMessageInfo

func (m *WaitQueueDoneRequest) GetContextId() uint64 {
	if m != nil {
		return m.ContextId
	}
	return 0
}

func (m *WaitQueueDoneRequest) GetOpId() []int64 {
	if m != nil {
		return m.OpId
	}
	return nil
}

type WaitQueueDoneResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WaitQueueDoneResponse) Reset()         { *m = WaitQueueDoneResponse{} }
func (m *WaitQueueDoneResponse) String() string { return proto.CompactTextString(m) }
func (*WaitQueueDoneResponse) ProtoMessage()    {}
func (*WaitQueueDoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f63cfa0a7bc4510, []int{9}
}

func (m *WaitQueueDoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaitQueueDoneResponse.Unmarshal(m, b)
}
func (m *WaitQueueDoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaitQueueDoneResponse.Marshal(b, m, deterministic)
}
func (m *WaitQueueDoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaitQueueDoneResponse.Merge(m, src)
}
func (m *WaitQueueDoneResponse) XXX_Size() int {
	return xxx_messageInfo_WaitQueueDoneResponse.Size(m)
}
func (m *WaitQueueDoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WaitQueueDoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WaitQueueDoneResponse proto.InternalMessageInfo

type KeepAliveRequest struct {
	ContextId            uint64   `protobuf:"fixed64,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeepAliveRequest) Reset()         { *m = KeepAliveRequest{} }
func (m *KeepAliveRequest) String() string { return proto.CompactTextString(m) }
func (*KeepAliveRequest) ProtoMessage()    {}
func (*KeepAliveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f63cfa0a7bc4510, []int{10}
}

func (m *KeepAliveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepAliveRequest.Unmarshal(m, b)
}
func (m *KeepAliveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepAliveRequest.Marshal(b, m, deterministic)
}
func (m *KeepAliveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepAliveRequest.Merge(m, src)
}
func (m *KeepAliveRequest) XXX_Size() int {
	return xxx_messageInfo_KeepAliveRequest.Size(m)
}
func (m *KeepAliveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepAliveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeepAliveRequest proto.InternalMessageInfo

func (m *KeepAliveRequest) GetContextId() uint64 {
	if m != nil {
		return m.ContextId
	}
	return 0
}

type KeepAliveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeepAliveResponse) Reset()         { *m = KeepAliveResponse{} }
func (m *KeepAliveResponse) String() string { return proto.CompactTextString(m) }
func (*KeepAliveResponse) ProtoMessage()    {}
func (*KeepAliveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f63cfa0a7bc4510, []int{11}
}

func (m *KeepAliveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepAliveResponse.Unmarshal(m, b)
}
func (m *KeepAliveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepAliveResponse.Marshal(b, m, deterministic)
}
func (m *KeepAliveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepAliveResponse.Merge(m, src)
}
func (m *KeepAliveResponse) XXX_Size() int {
	return xxx_messageInfo_KeepAliveResponse.Size(m)
}
func (m *KeepAliveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepAliveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeepAliveResponse proto.InternalMessageInfo

type CloseContextRequest struct {
	ContextId            uint64   `protobuf:"fixed64,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseContextRequest) Reset()         { *m = CloseContextRequest{} }
func (m *CloseContextRequest) String() string { return proto.CompactTextString(m) }
func (*CloseContextRequest) ProtoMessage()    {}
func (*CloseContextRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f63cfa0a7bc4510, []int{12}
}

func (m *CloseContextRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseContextRequest.Unmarshal(m, b)
}
func (m *CloseContextRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseContextRequest.Marshal(b, m, deterministic)
}
func (m *CloseContextRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseContextRequest.Merge(m, src)
}
func (m *CloseContextRequest) XXX_Size() int {
	return xxx_messageInfo_CloseContextRequest.Size(m)
}
func (m *CloseContextRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseContextRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseContextRequest proto.InternalMessageInfo

func (m *CloseContextRequest) GetContextId() uint64 {
	if m != nil {
		return m.ContextId
	}
	return 0
}

type CloseContextResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseContextResponse) Reset()         { *m = CloseContextResponse{} }
func (m *CloseContextResponse) String() string { return proto.CompactTextString(m) }
func (*CloseContextResponse) ProtoMessage()    {}
func (*CloseContextResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f63cfa0a7bc4510, []int{13}
}

func (m *CloseContextResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseContextResponse.Unmarshal(m, b)
}
func (m *CloseContextResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseContextResponse.Marshal(b, m, deterministic)
}
func (m *CloseContextResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseContextResponse.Merge(m, src)
}
func (m *CloseContextResponse) XXX_Size() int {
	return xxx_messageInfo_CloseContextResponse.Size(m)
}
func (m *CloseContextResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseContextResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloseContextResponse proto.InternalMessageInfo

type RegisterFunctionRequest struct {
	ContextId            uint64                 `protobuf:"fixed64,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	FunctionDef          *framework.FunctionDef `protobuf:"bytes,2,opt,name=function_def,json=functionDef,proto3" json:"function_def,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RegisterFunctionRequest) Reset()         { *m = RegisterFunctionRequest{} }
func (m *RegisterFunctionRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterFunctionRequest) ProtoMessage()    {}
func (*RegisterFunctionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f63cfa0a7bc4510, []int{14}
}

func (m *RegisterFunctionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterFunctionRequest.Unmarshal(m, b)
}
func (m *RegisterFunctionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterFunctionRequest.Marshal(b, m, deterministic)
}
func (m *RegisterFunctionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterFunctionRequest.Merge(m, src)
}
func (m *RegisterFunctionRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterFunctionRequest.Size(m)
}
func (m *RegisterFunctionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterFunctionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterFunctionRequest proto.InternalMessageInfo

func (m *RegisterFunctionRequest) GetContextId() uint64 {
	if m != nil {
		return m.ContextId
	}
	return 0
}

func (m *RegisterFunctionRequest) GetFunctionDef() *framework.FunctionDef {
	if m != nil {
		return m.FunctionDef
	}
	return nil
}

type RegisterFunctionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterFunctionResponse) Reset()         { *m = RegisterFunctionResponse{} }
func (m *RegisterFunctionResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterFunctionResponse) ProtoMessage()    {}
func (*RegisterFunctionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f63cfa0a7bc4510, []int{15}
}

func (m *RegisterFunctionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterFunctionResponse.Unmarshal(m, b)
}
func (m *RegisterFunctionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterFunctionResponse.Marshal(b, m, deterministic)
}
func (m *RegisterFunctionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterFunctionResponse.Merge(m, src)
}
func (m *RegisterFunctionResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterFunctionResponse.Size(m)
}
func (m *RegisterFunctionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterFunctionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterFunctionResponse proto.InternalMessageInfo

type SendTensorRequest struct {
	ContextId uint64 `protobuf:"fixed64,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	// All remote tensors are identified by <Op ID, Output num>. To mimic this
	// situation when directly sending tensors, we include an "artificial" op ID
	// (which would have corresponded to the _Recv op when not using SendTensor).
	OpId int64 `protobuf:"varint,2,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	// The index within the repeated field is the output number that will help
	// uniquely identify (along with the above op_id) the particular tensor.
	Tensors []*framework.TensorProto `protobuf:"bytes,3,rep,name=tensors,proto3" json:"tensors,omitempty"`
	// The device on which the tensors should be resident.
	DeviceName           string   `protobuf:"bytes,4,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTensorRequest) Reset()         { *m = SendTensorRequest{} }
func (m *SendTensorRequest) String() string { return proto.CompactTextString(m) }
func (*SendTensorRequest) ProtoMessage()    {}
func (*SendTensorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f63cfa0a7bc4510, []int{16}
}

func (m *SendTensorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTensorRequest.Unmarshal(m, b)
}
func (m *SendTensorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTensorRequest.Marshal(b, m, deterministic)
}
func (m *SendTensorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTensorRequest.Merge(m, src)
}
func (m *SendTensorRequest) XXX_Size() int {
	return xxx_messageInfo_SendTensorRequest.Size(m)
}
func (m *SendTensorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTensorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendTensorRequest proto.InternalMessageInfo

func (m *SendTensorRequest) GetContextId() uint64 {
	if m != nil {
		return m.ContextId
	}
	return 0
}

func (m *SendTensorRequest) GetOpId() int64 {
	if m != nil {
		return m.OpId
	}
	return 0
}

func (m *SendTensorRequest) GetTensors() []*framework.TensorProto {
	if m != nil {
		return m.Tensors
	}
	return nil
}

func (m *SendTensorRequest) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

type SendTensorResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTensorResponse) Reset()         { *m = SendTensorResponse{} }
func (m *SendTensorResponse) String() string { return proto.CompactTextString(m) }
func (*SendTensorResponse) ProtoMessage()    {}
func (*SendTensorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f63cfa0a7bc4510, []int{17}
}

func (m *SendTensorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTensorResponse.Unmarshal(m, b)
}
func (m *SendTensorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTensorResponse.Marshal(b, m, deterministic)
}
func (m *SendTensorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTensorResponse.Merge(m, src)
}
func (m *SendTensorResponse) XXX_Size() int {
	return xxx_messageInfo_SendTensorResponse.Size(m)
}
func (m *SendTensorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTensorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendTensorResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RemoteTensorHandle)(nil), "tensorflow.eager.RemoteTensorHandle")
	proto.RegisterType((*Operation)(nil), "tensorflow.eager.Operation")
	proto.RegisterMapType((map[string]*framework.AttrValue)(nil), "tensorflow.eager.Operation.AttrsEntry")
	proto.RegisterType((*QueueItem)(nil), "tensorflow.eager.QueueItem")
	proto.RegisterType((*QueueResponse)(nil), "tensorflow.eager.QueueResponse")
	proto.RegisterType((*CreateContextRequest)(nil), "tensorflow.eager.CreateContextRequest")
	proto.RegisterType((*CreateContextResponse)(nil), "tensorflow.eager.CreateContextResponse")
	proto.RegisterType((*EnqueueRequest)(nil), "tensorflow.eager.EnqueueRequest")
	proto.RegisterType((*EnqueueResponse)(nil), "tensorflow.eager.EnqueueResponse")
	proto.RegisterType((*WaitQueueDoneRequest)(nil), "tensorflow.eager.WaitQueueDoneRequest")
	proto.RegisterType((*WaitQueueDoneResponse)(nil), "tensorflow.eager.WaitQueueDoneResponse")
	proto.RegisterType((*KeepAliveRequest)(nil), "tensorflow.eager.KeepAliveRequest")
	proto.RegisterType((*KeepAliveResponse)(nil), "tensorflow.eager.KeepAliveResponse")
	proto.RegisterType((*CloseContextRequest)(nil), "tensorflow.eager.CloseContextRequest")
	proto.RegisterType((*CloseContextResponse)(nil), "tensorflow.eager.CloseContextResponse")
	proto.RegisterType((*RegisterFunctionRequest)(nil), "tensorflow.eager.RegisterFunctionRequest")
	proto.RegisterType((*RegisterFunctionResponse)(nil), "tensorflow.eager.RegisterFunctionResponse")
	proto.RegisterType((*SendTensorRequest)(nil), "tensorflow.eager.SendTensorRequest")
	proto.RegisterType((*SendTensorResponse)(nil), "tensorflow.eager.SendTensorResponse")
}

func init() {
	proto.RegisterFile("tensorflow/core/protobuf/eager_service.proto", fileDescriptor_7f63cfa0a7bc4510)
}

var fileDescriptor_7f63cfa0a7bc4510 = []byte{
	// 1033 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdb, 0x6e, 0xdb, 0x46,
	0x13, 0x0e, 0x25, 0x51, 0xb6, 0xc6, 0x87, 0xc8, 0xeb, 0x93, 0x7e, 0xfe, 0x2d, 0xa2, 0xb2, 0xae,
	0xab, 0xa6, 0x81, 0x1d, 0xbb, 0x01, 0x5a, 0xa4, 0xb9, 0x71, 0x6d, 0x07, 0xb6, 0x0b, 0xd8, 0xe9,
	0xca, 0x48, 0x5a, 0x14, 0x05, 0x4b, 0x93, 0x23, 0x9b, 0xb0, 0xc4, 0x65, 0xc8, 0xa5, 0x53, 0x3f,
	0x4b, 0xef, 0xfa, 0x18, 0xbd, 0xec, 0x53, 0xf5, 0xb2, 0xd8, 0x83, 0x4e, 0x24, 0x65, 0xa9, 0x40,
	0xef, 0xa8, 0xd9, 0x6f, 0x66, 0xbe, 0x99, 0x9d, 0x6f, 0x56, 0xf0, 0x8c, 0x63, 0x98, 0xb0, 0xb8,
	0xd3, 0x65, 0x1f, 0x76, 0x3d, 0x16, 0xe3, 0x6e, 0x14, 0x33, 0xce, 0xae, 0xd2, 0xce, 0x2e, 0xba,
	0xd7, 0x18, 0x3b, 0x09, 0xc6, 0x77, 0x81, 0x87, 0x3b, 0xd2, 0x4c, 0xea, 0x43, 0xf4, 0x8e, 0x3c,
	0xb7, 0x9e, 0x66, 0xfd, 0x3b, 0xb1, 0xdb, 0xc3, 0x0f, 0x2c, 0xbe, 0xdd, 0x75, 0x39, 0x8f, 0x9d,
	0x3b, 0xb7, 0x9b, 0x6a, 0x6f, 0x6b, 0x6f, 0x32, 0xd6, 0x47, 0x91, 0xc5, 0x11, 0x2e, 0xc1, 0x55,
	0xca, 0x31, 0xd1, 0x2e, 0xad, 0xc9, 0x2e, 0x9d, 0x34, 0xf4, 0x78, 0xc0, 0x42, 0x8d, 0xdc, 0x9e,
	0x8c, 0x54, 0x27, 0x1a, 0xf7, 0x6c, 0x1a, 0xce, 0x49, 0x6e, 0xdc, 0x08, 0xa7, 0xe7, 0xbf, 0xc3,
	0x38, 0x09, 0x58, 0xd8, 0x67, 0xfa, 0x7c, 0x62, 0x23, 0x87, 0x07, 0xb2, 0x9b, 0xa8, 0x99, 0xd8,
	0x27, 0x40, 0x28, 0xf6, 0x18, 0xc7, 0x4b, 0x09, 0x38, 0x71, 0x43, 0xbf, 0x8b, 0x64, 0x15, 0x4c,
	0x16, 0x39, 0x81, 0xdf, 0x30, 0x9a, 0x46, 0xab, 0x4c, 0x2b, 0x2c, 0x3a, 0xf5, 0xc9, 0xc7, 0x00,
	0x2c, 0xe5, 0x51, 0xca, 0x9d, 0x30, 0xed, 0x35, 0x4a, 0x4d, 0xa3, 0x65, 0xd2, 0x9a, 0xb2, 0x9c,
	0xa7, 0x3d, 0xfb, 0xcf, 0x12, 0xd4, 0x2e, 0x22, 0x8c, 0x5d, 0xd1, 0x0f, 0xb2, 0x0c, 0xa5, 0x81,
	0x7b, 0x29, 0xf0, 0x09, 0x81, 0x4a, 0xe8, 0xf6, 0x50, 0xba, 0xd5, 0xa8, 0xfc, 0x26, 0xaf, 0xa0,
	0x1a, 0x84, 0x51, 0xca, 0x93, 0x46, 0xb9, 0x59, 0x6e, 0x2d, 0xec, 0x6f, 0xed, 0x64, 0x6f, 0x76,
	0x27, 0xcf, 0x8d, 0x6a, 0x1f, 0xb2, 0x05, 0xcb, 0x1e, 0x0b, 0x79, 0xcc, 0xba, 0x8e, 0xe4, 0x9a,
	0x34, 0x2a, 0xcd, 0x72, 0xab, 0x4c, 0x17, 0xb5, 0xf5, 0x22, 0x3a, 0xf5, 0x13, 0xf2, 0x0a, 0x4c,
	0x71, 0x9f, 0x49, 0xc3, 0x94, 0x29, 0xb6, 0xf3, 0x29, 0x06, 0x9c, 0x77, 0x0e, 0x04, 0xf0, 0x38,
	0xe4, 0xf1, 0x3d, 0x55, 0x4e, 0x64, 0x03, 0xaa, 0x6a, 0x28, 0x1a, 0x55, 0xc9, 0x5b, 0xff, 0xb2,
	0x2e, 0x00, 0x86, 0x60, 0x52, 0x87, 0xf2, 0x2d, 0xde, 0xcb, 0x62, 0x6b, 0x54, 0x7c, 0x92, 0x2f,
	0xc1, 0x94, 0x33, 0x27, 0xcb, 0x5d, 0xd8, 0x5f, 0x1f, 0xcd, 0x2a, 0x1c, 0xdf, 0x8a, 0x43, 0xaa,
	0x30, 0x2f, 0x4b, 0xdf, 0x18, 0xf6, 0x1f, 0x06, 0xd4, 0x7e, 0x48, 0x31, 0xc5, 0x53, 0x8e, 0x3d,
	0xf2, 0x06, 0xea, 0x37, 0xb2, 0x58, 0x87, 0x33, 0xc7, 0x47, 0x2f, 0xc6, 0x8e, 0x8c, 0x3e, 0x63,
	0x8b, 0x4e, 0x1e, 0xd1, 0x65, 0xe5, 0x7f, 0xc9, 0x8e, 0xa4, 0x37, 0xf9, 0x16, 0x6a, 0xac, 0x5f,
	0xa7, 0x26, 0xf5, 0xff, 0x07, 0x5a, 0x71, 0xf2, 0x88, 0x0e, 0xf1, 0xdf, 0x55, 0xa1, 0x12, 0x70,
	0xec, 0xd9, 0x87, 0xb0, 0x24, 0x39, 0x52, 0x4c, 0x22, 0x16, 0x26, 0x48, 0xf6, 0xc1, 0x94, 0x73,
	0xda, 0x30, 0x64, 0x73, 0x3f, 0x1a, 0x8d, 0xa8, 0x08, 0xb5, 0xc5, 0xf1, 0x1b, 0x31, 0x69, 0x54,
	0x41, 0xed, 0xbf, 0x4a, 0xb0, 0x76, 0x18, 0xa3, 0xcb, 0xf1, 0x90, 0x85, 0x1c, 0x7f, 0xe3, 0x14,
	0xdf, 0xa7, 0x98, 0x70, 0xf2, 0x02, 0x40, 0x4d, 0xa6, 0xe3, 0x0f, 0xca, 0x1d, 0x6b, 0x5c, 0x5b,
	0x9e, 0x1e, 0x61, 0x87, 0xd6, 0x92, 0xfe, 0x27, 0x59, 0x03, 0xd3, 0x4d, 0xee, 0x43, 0x4f, 0x16,
	0x35, 0x4f, 0xd5, 0x0f, 0xb2, 0x0d, 0x8f, 0x6f, 0x11, 0x23, 0xc7, 0xed, 0x06, 0x77, 0xe8, 0x24,
	0xe8, 0x89, 0x11, 0x13, 0xa3, 0xb8, 0x24, 0xcc, 0x07, 0xc2, 0xda, 0x46, 0x2f, 0x21, 0x5f, 0xc3,
	0x82, 0x56, 0x90, 0x4c, 0x5a, 0x91, 0x49, 0x37, 0x46, 0x93, 0xbe, 0x55, 0xc7, 0x22, 0x2b, 0xdc,
	0x0d, 0xbe, 0xc9, 0x8f, 0xf0, 0x3f, 0xaf, 0x9b, 0x26, 0x5c, 0xb2, 0xcd, 0x6c, 0x8d, 0x46, 0x35,
	0xdf, 0x8d, 0x23, 0x09, 0x3a, 0x18, 0x60, 0xe8, 0xa6, 0x76, 0xcf, 0x1e, 0x08, 0x95, 0x79, 0xaa,
	0x31, 0x42, 0x7f, 0x73, 0x4d, 0xa3, 0x55, 0xa5, 0x35, 0x6d, 0x39, 0xf5, 0xcf, 0x2a, 0xf3, 0x66,
	0xbd, 0x6a, 0xdf, 0xc0, 0x7a, 0xa6, 0x87, 0xfa, 0x46, 0x4e, 0x61, 0x25, 0xcf, 0xa7, 0x34, 0x03,
	0x9f, 0xba, 0x9f, 0xb1, 0x9c, 0x55, 0xe6, 0x8d, 0x7a, 0xc9, 0xbe, 0x82, 0xe5, 0xe3, 0xf0, 0xbd,
	0xba, 0x75, 0x75, 0x4f, 0xe3, 0x04, 0x8d, 0x0c, 0x41, 0xb2, 0x07, 0xa6, 0x84, 0x6b, 0x4d, 0x17,
	0x4c, 0xd9, 0x60, 0xce, 0xa9, 0x42, 0xda, 0x3f, 0xc1, 0xe3, 0x41, 0x0e, 0x5d, 0xc7, 0x6b, 0x58,
	0x96, 0x06, 0x27, 0xd6, 0x16, 0x3d, 0x62, 0x4f, 0x26, 0x84, 0xeb, 0x3b, 0xd2, 0xa5, 0xb1, 0x38,
	0xf6, 0x19, 0xac, 0xbd, 0x73, 0x03, 0x2e, 0x31, 0x47, 0x2c, 0x9c, 0xb5, 0x88, 0xc1, 0xfe, 0x2b,
	0xc9, 0x95, 0x22, 0xf7, 0x9f, 0xbd, 0x09, 0xeb, 0x99, 0x58, 0x3a, 0xc9, 0x1e, 0xd4, 0xbf, 0xef,
	0x8f, 0xd5, 0x6c, 0x09, 0xec, 0x55, 0x58, 0x19, 0x71, 0xd1, 0x71, 0x5e, 0xc0, 0xea, 0x61, 0x97,
	0x25, 0x59, 0x61, 0x4c, 0x09, 0xb5, 0x01, 0x6b, 0xe3, 0x5e, 0x3a, 0x1a, 0x87, 0x4d, 0x8a, 0xd7,
	0x81, 0x18, 0xb2, 0xd7, 0xfa, 0x95, 0x9a, 0xb1, 0xfa, 0x97, 0xb0, 0xd8, 0x7f, 0xd7, 0xa4, 0x2c,
	0xd4, 0xbe, 0xd8, 0x1c, 0x6d, 0x7d, 0x3f, 0xa2, 0xd0, 0xc5, 0x42, 0x67, 0xf8, 0xc3, 0xb6, 0xa0,
	0x91, 0xcf, 0xaa, 0x19, 0xfd, 0x6e, 0xc0, 0x4a, 0x1b, 0x43, 0x5f, 0xad, 0x86, 0x7f, 0x7f, 0x15,
	0xc3, 0xa7, 0x68, 0x0f, 0xe6, 0x14, 0x99, 0xfe, 0xd3, 0xb1, 0x99, 0x5f, 0x3d, 0x6a, 0xeb, 0xf4,
	0x71, 0xe4, 0x09, 0x2c, 0x68, 0x65, 0xc8, 0x77, 0xa8, 0x22, 0x97, 0x35, 0x28, 0xd3, 0xb9, 0xdb,
	0x43, 0x7b, 0x0d, 0xc8, 0x28, 0x39, 0xc5, 0x79, 0xff, 0x6f, 0x13, 0x16, 0x8f, 0xc5, 0x9c, 0xb5,
	0xd5, 0x7f, 0x10, 0xf2, 0x2b, 0x2c, 0x8d, 0x49, 0x8f, 0x14, 0x3c, 0x29, 0x45, 0xfb, 0xcd, 0xfa,
	0x7c, 0x2a, 0x4e, 0xcf, 0xfe, 0x39, 0xcc, 0x69, 0x39, 0x90, 0x66, 0xde, 0x67, 0x5c, 0x8d, 0xd6,
	0x27, 0x0f, 0x20, 0x74, 0xbc, 0x9f, 0xa1, 0xde, 0xe6, 0x31, 0xba, 0xbd, 0x20, 0xbc, 0xfe, 0x2f,
	0x03, 0xb7, 0x8c, 0xe7, 0x86, 0x68, 0xc7, 0x98, 0x28, 0x8a, 0xda, 0x51, 0xa4, 0xc0, 0xa2, 0x76,
	0x14, 0xaa, 0x8b, 0x5c, 0x42, 0x6d, 0x20, 0x15, 0x62, 0xe7, 0xbd, 0xb2, 0xd2, 0xb3, 0x3e, 0x7d,
	0x10, 0xa3, 0xa3, 0xfe, 0x02, 0x8b, 0xa3, 0xaa, 0x21, 0x9f, 0x15, 0xdc, 0x4e, 0x5e, 0x8b, 0xd6,
	0xf6, 0x34, 0x98, 0x0e, 0x1f, 0x40, 0x3d, 0x2b, 0x03, 0xf2, 0x45, 0xd1, 0xdb, 0x5d, 0x28, 0x50,
	0xeb, 0xe9, 0x2c, 0x50, 0x9d, 0xea, 0x1d, 0xc0, 0x70, 0x6e, 0x49, 0x41, 0xf1, 0x39, 0xc9, 0x59,
	0x5b, 0x0f, 0x83, 0x54, 0xe0, 0xab, 0xaa, 0xfc, 0x87, 0xf8, 0xd5, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xbd, 0xb8, 0x3d, 0x22, 0x9e, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EagerServiceClient is the client API for EagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EagerServiceClient interface {
	// This initializes the worker, informing it about the other workers in the
	// cluster and exchanging authentication tokens which will be used in all
	// other RPCs to detect whether the worker has restarted.
	CreateContext(ctx context.Context, in *CreateContextRequest, opts ...grpc.CallOption) (*CreateContextResponse, error)
	// This takes a list of Execute and DeleteTensorHandle operations and enqueues
	// (in async mode) or executes (in sync mode) them on the remote server.
	// All outputs of ops which were not explicitly deleted with
	// DeleteTensorHandle entries will be assumed to be alive and are usable by
	// future calls to Enqueue.
	Enqueue(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error)
	// A streaming version of Enqueue.
	// Current server implementation sends one response per received request.
	// The benefit for using a streaming version is that subsequent requests
	// can be sent without waiting for a response to the previous request. This
	// synchronization is required in the regular Enqueue call because gRPC does
	// not guarantee to preserve request order.
	StreamingEnqueue(ctx context.Context, opts ...grpc.CallOption) (EagerService_StreamingEnqueueClient, error)
	// Takes a set of op IDs and waits until those ops are done. Returns any error
	// in the stream so far.
	WaitQueueDone(ctx context.Context, in *WaitQueueDoneRequest, opts ...grpc.CallOption) (*WaitQueueDoneResponse, error)
	// Contexts are always created with a deadline and no RPCs within a deadline
	// will trigger a context garbage collection. KeepAlive calls can be used to
	// delay this.
	KeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*KeepAliveResponse, error)
	// Closes the context. No calls to other methods using the existing context ID
	// are valid after this.
	CloseContext(ctx context.Context, in *CloseContextRequest, opts ...grpc.CallOption) (*CloseContextResponse, error)
	// Takes a FunctionDef and makes it enqueable on the remote worker.
	RegisterFunction(ctx context.Context, in *RegisterFunctionRequest, opts ...grpc.CallOption) (*RegisterFunctionResponse, error)
	// An RPC to push tensors to the server. At times, certain environments don't
	// allow the server to connect back to the client.
	SendTensor(ctx context.Context, in *SendTensorRequest, opts ...grpc.CallOption) (*SendTensorResponse, error)
}

type eagerServiceClient struct {
	cc *grpc.ClientConn
}

func NewEagerServiceClient(cc *grpc.ClientConn) EagerServiceClient {
	return &eagerServiceClient{cc}
}

func (c *eagerServiceClient) CreateContext(ctx context.Context, in *CreateContextRequest, opts ...grpc.CallOption) (*CreateContextResponse, error) {
	out := new(CreateContextResponse)
	err := c.cc.Invoke(ctx, "/tensorflow.eager.EagerService/CreateContext", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eagerServiceClient) Enqueue(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error) {
	out := new(EnqueueResponse)
	err := c.cc.Invoke(ctx, "/tensorflow.eager.EagerService/Enqueue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eagerServiceClient) StreamingEnqueue(ctx context.Context, opts ...grpc.CallOption) (EagerService_StreamingEnqueueClient, error) {
	stream, err := c.cc.NewStream(ctx, &_EagerService_serviceDesc.Streams[0], "/tensorflow.eager.EagerService/StreamingEnqueue", opts...)
	if err != nil {
		return nil, err
	}
	x := &eagerServiceStreamingEnqueueClient{stream}
	return x, nil
}

type EagerService_StreamingEnqueueClient interface {
	Send(*EnqueueRequest) error
	Recv() (*EnqueueResponse, error)
	grpc.ClientStream
}

type eagerServiceStreamingEnqueueClient struct {
	grpc.ClientStream
}

func (x *eagerServiceStreamingEnqueueClient) Send(m *EnqueueRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *eagerServiceStreamingEnqueueClient) Recv() (*EnqueueResponse, error) {
	m := new(EnqueueResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *eagerServiceClient) WaitQueueDone(ctx context.Context, in *WaitQueueDoneRequest, opts ...grpc.CallOption) (*WaitQueueDoneResponse, error) {
	out := new(WaitQueueDoneResponse)
	err := c.cc.Invoke(ctx, "/tensorflow.eager.EagerService/WaitQueueDone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eagerServiceClient) KeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*KeepAliveResponse, error) {
	out := new(KeepAliveResponse)
	err := c.cc.Invoke(ctx, "/tensorflow.eager.EagerService/KeepAlive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eagerServiceClient) CloseContext(ctx context.Context, in *CloseContextRequest, opts ...grpc.CallOption) (*CloseContextResponse, error) {
	out := new(CloseContextResponse)
	err := c.cc.Invoke(ctx, "/tensorflow.eager.EagerService/CloseContext", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eagerServiceClient) RegisterFunction(ctx context.Context, in *RegisterFunctionRequest, opts ...grpc.CallOption) (*RegisterFunctionResponse, error) {
	out := new(RegisterFunctionResponse)
	err := c.cc.Invoke(ctx, "/tensorflow.eager.EagerService/RegisterFunction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eagerServiceClient) SendTensor(ctx context.Context, in *SendTensorRequest, opts ...grpc.CallOption) (*SendTensorResponse, error) {
	out := new(SendTensorResponse)
	err := c.cc.Invoke(ctx, "/tensorflow.eager.EagerService/SendTensor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EagerServiceServer is the server API for EagerService service.
type EagerServiceServer interface {
	// This initializes the worker, informing it about the other workers in the
	// cluster and exchanging authentication tokens which will be used in all
	// other RPCs to detect whether the worker has restarted.
	CreateContext(context.Context, *CreateContextRequest) (*CreateContextResponse, error)
	// This takes a list of Execute and DeleteTensorHandle operations and enqueues
	// (in async mode) or executes (in sync mode) them on the remote server.
	// All outputs of ops which were not explicitly deleted with
	// DeleteTensorHandle entries will be assumed to be alive and are usable by
	// future calls to Enqueue.
	Enqueue(context.Context, *EnqueueRequest) (*EnqueueResponse, error)
	// A streaming version of Enqueue.
	// Current server implementation sends one response per received request.
	// The benefit for using a streaming version is that subsequent requests
	// can be sent without waiting for a response to the previous request. This
	// synchronization is required in the regular Enqueue call because gRPC does
	// not guarantee to preserve request order.
	StreamingEnqueue(EagerService_StreamingEnqueueServer) error
	// Takes a set of op IDs and waits until those ops are done. Returns any error
	// in the stream so far.
	WaitQueueDone(context.Context, *WaitQueueDoneRequest) (*WaitQueueDoneResponse, error)
	// Contexts are always created with a deadline and no RPCs within a deadline
	// will trigger a context garbage collection. KeepAlive calls can be used to
	// delay this.
	KeepAlive(context.Context, *KeepAliveRequest) (*KeepAliveResponse, error)
	// Closes the context. No calls to other methods using the existing context ID
	// are valid after this.
	CloseContext(context.Context, *CloseContextRequest) (*CloseContextResponse, error)
	// Takes a FunctionDef and makes it enqueable on the remote worker.
	RegisterFunction(context.Context, *RegisterFunctionRequest) (*RegisterFunctionResponse, error)
	// An RPC to push tensors to the server. At times, certain environments don't
	// allow the server to connect back to the client.
	SendTensor(context.Context, *SendTensorRequest) (*SendTensorResponse, error)
}

// UnimplementedEagerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEagerServiceServer struct {
}

func (*UnimplementedEagerServiceServer) CreateContext(ctx context.Context, req *CreateContextRequest) (*CreateContextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateContext not implemented")
}
func (*UnimplementedEagerServiceServer) Enqueue(ctx context.Context, req *EnqueueRequest) (*EnqueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enqueue not implemented")
}
func (*UnimplementedEagerServiceServer) StreamingEnqueue(srv EagerService_StreamingEnqueueServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamingEnqueue not implemented")
}
func (*UnimplementedEagerServiceServer) WaitQueueDone(ctx context.Context, req *WaitQueueDoneRequest) (*WaitQueueDoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitQueueDone not implemented")
}
func (*UnimplementedEagerServiceServer) KeepAlive(ctx context.Context, req *KeepAliveRequest) (*KeepAliveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeepAlive not implemented")
}
func (*UnimplementedEagerServiceServer) CloseContext(ctx context.Context, req *CloseContextRequest) (*CloseContextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseContext not implemented")
}
func (*UnimplementedEagerServiceServer) RegisterFunction(ctx context.Context, req *RegisterFunctionRequest) (*RegisterFunctionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterFunction not implemented")
}
func (*UnimplementedEagerServiceServer) SendTensor(ctx context.Context, req *SendTensorRequest) (*SendTensorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTensor not implemented")
}

func RegisterEagerServiceServer(s *grpc.Server, srv EagerServiceServer) {
	s.RegisterService(&_EagerService_serviceDesc, srv)
}

func _EagerService_CreateContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EagerServiceServer).CreateContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tensorflow.eager.EagerService/CreateContext",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EagerServiceServer).CreateContext(ctx, req.(*CreateContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EagerService_Enqueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EagerServiceServer).Enqueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tensorflow.eager.EagerService/Enqueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EagerServiceServer).Enqueue(ctx, req.(*EnqueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EagerService_StreamingEnqueue_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EagerServiceServer).StreamingEnqueue(&eagerServiceStreamingEnqueueServer{stream})
}

type EagerService_StreamingEnqueueServer interface {
	Send(*EnqueueResponse) error
	Recv() (*EnqueueRequest, error)
	grpc.ServerStream
}

type eagerServiceStreamingEnqueueServer struct {
	grpc.ServerStream
}

func (x *eagerServiceStreamingEnqueueServer) Send(m *EnqueueResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *eagerServiceStreamingEnqueueServer) Recv() (*EnqueueRequest, error) {
	m := new(EnqueueRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _EagerService_WaitQueueDone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitQueueDoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EagerServiceServer).WaitQueueDone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tensorflow.eager.EagerService/WaitQueueDone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EagerServiceServer).WaitQueueDone(ctx, req.(*WaitQueueDoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EagerService_KeepAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeepAliveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EagerServiceServer).KeepAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tensorflow.eager.EagerService/KeepAlive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EagerServiceServer).KeepAlive(ctx, req.(*KeepAliveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EagerService_CloseContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EagerServiceServer).CloseContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tensorflow.eager.EagerService/CloseContext",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EagerServiceServer).CloseContext(ctx, req.(*CloseContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EagerService_RegisterFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EagerServiceServer).RegisterFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tensorflow.eager.EagerService/RegisterFunction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EagerServiceServer).RegisterFunction(ctx, req.(*RegisterFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EagerService_SendTensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EagerServiceServer).SendTensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tensorflow.eager.EagerService/SendTensor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EagerServiceServer).SendTensor(ctx, req.(*SendTensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EagerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tensorflow.eager.EagerService",
	HandlerType: (*EagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateContext",
			Handler:    _EagerService_CreateContext_Handler,
		},
		{
			MethodName: "Enqueue",
			Handler:    _EagerService_Enqueue_Handler,
		},
		{
			MethodName: "WaitQueueDone",
			Handler:    _EagerService_WaitQueueDone_Handler,
		},
		{
			MethodName: "KeepAlive",
			Handler:    _EagerService_KeepAlive_Handler,
		},
		{
			MethodName: "CloseContext",
			Handler:    _EagerService_CloseContext_Handler,
		},
		{
			MethodName: "RegisterFunction",
			Handler:    _EagerService_RegisterFunction_Handler,
		},
		{
			MethodName: "SendTensor",
			Handler:    _EagerService_SendTensor_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamingEnqueue",
			Handler:       _EagerService_StreamingEnqueue_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "tensorflow/core/protobuf/eager_service.proto",
}
