// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tensorflow_serving/resources/resources.proto

package tensorflow_serving

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// One kind of resource on one device (or type of device).
type Resource struct {
	// The type of device on which the resource resides, e.g. CPU or GPU.
	Device string `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	// A specific instance of the device of type 'device' to which the resources
	// are bound (instances are assumed to be numbered 0, 1, ...).
	//
	// When representing the resources required by a servable that has yet to be
	// loaded, this field is optional. If not set, it denotes that the servable's
	// resources are not (yet) bound to a specific instance.
	DeviceInstance *wrappers.UInt32Value `protobuf:"bytes,2,opt,name=device_instance,json=deviceInstance,proto3" json:"device_instance,omitempty"`
	// The kind of resource on the device (instance), e.g. RAM or compute share.
	//
	// A given type of resource should have a standard unit that represents the
	// smallest useful quantization. We strongly recommend including the unit
	// (e.g. bytes or millicores) in this string, as in "ram_bytes".
	Kind                 string   `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_77c3fea95db5aeaa, []int{0}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *Resource) GetDeviceInstance() *wrappers.UInt32Value {
	if m != nil {
		return m.DeviceInstance
	}
	return nil
}

func (m *Resource) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

// An allocation of one or more kinds of resources, along with the quantity of
// each. Used to denote the resources that a servable (or collection of
// servables) will use or is currently using. Also used to denote resources
// available to the serving system for loading more servables.
type ResourceAllocation struct {
	ResourceQuantities   []*ResourceAllocation_Entry `protobuf:"bytes,1,rep,name=resource_quantities,json=resourceQuantities,proto3" json:"resource_quantities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ResourceAllocation) Reset()         { *m = ResourceAllocation{} }
func (m *ResourceAllocation) String() string { return proto.CompactTextString(m) }
func (*ResourceAllocation) ProtoMessage()    {}
func (*ResourceAllocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_77c3fea95db5aeaa, []int{1}
}

func (m *ResourceAllocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceAllocation.Unmarshal(m, b)
}
func (m *ResourceAllocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceAllocation.Marshal(b, m, deterministic)
}
func (m *ResourceAllocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceAllocation.Merge(m, src)
}
func (m *ResourceAllocation) XXX_Size() int {
	return xxx_messageInfo_ResourceAllocation.Size(m)
}
func (m *ResourceAllocation) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceAllocation.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceAllocation proto.InternalMessageInfo

func (m *ResourceAllocation) GetResourceQuantities() []*ResourceAllocation_Entry {
	if m != nil {
		return m.ResourceQuantities
	}
	return nil
}

// A collection of resources, each with a quantity. Treated as a resource->
// quantity map, i.e. no resource can repeat and the order is immaterial.
type ResourceAllocation_Entry struct {
	Resource             *Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Quantity             uint64    `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ResourceAllocation_Entry) Reset()         { *m = ResourceAllocation_Entry{} }
func (m *ResourceAllocation_Entry) String() string { return proto.CompactTextString(m) }
func (*ResourceAllocation_Entry) ProtoMessage()    {}
func (*ResourceAllocation_Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_77c3fea95db5aeaa, []int{1, 0}
}

func (m *ResourceAllocation_Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceAllocation_Entry.Unmarshal(m, b)
}
func (m *ResourceAllocation_Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceAllocation_Entry.Marshal(b, m, deterministic)
}
func (m *ResourceAllocation_Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceAllocation_Entry.Merge(m, src)
}
func (m *ResourceAllocation_Entry) XXX_Size() int {
	return xxx_messageInfo_ResourceAllocation_Entry.Size(m)
}
func (m *ResourceAllocation_Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceAllocation_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceAllocation_Entry proto.InternalMessageInfo

func (m *ResourceAllocation_Entry) GetResource() *Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *ResourceAllocation_Entry) GetQuantity() uint64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func init() {
	proto.RegisterType((*Resource)(nil), "tensorflow.serving.Resource")
	proto.RegisterType((*ResourceAllocation)(nil), "tensorflow.serving.ResourceAllocation")
	proto.RegisterType((*ResourceAllocation_Entry)(nil), "tensorflow.serving.ResourceAllocation.Entry")
}

func init() {
	proto.RegisterFile("tensorflow_serving/resources/resources.proto", fileDescriptor_77c3fea95db5aeaa)
}

var fileDescriptor_77c3fea95db5aeaa = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x31, 0x6b, 0xfb, 0x30,
	0x10, 0xc5, 0xf1, 0x3f, 0xf9, 0x07, 0xf7, 0x02, 0x2d, 0x5c, 0xa1, 0x18, 0x53, 0x8a, 0xc9, 0xe4,
	0x21, 0xc8, 0xe0, 0x2c, 0x5d, 0x3b, 0x64, 0xc8, 0x58, 0x41, 0xbb, 0x05, 0xe3, 0x38, 0x17, 0x23,
	0x6a, 0x24, 0x57, 0x92, 0x13, 0x32, 0xf4, 0x4b, 0xf6, 0x13, 0x95, 0xca, 0xb2, 0x33, 0x04, 0xba,
	0xbd, 0xe3, 0xde, 0xfb, 0x49, 0xef, 0x60, 0x69, 0x49, 0x1a, 0xa5, 0x0f, 0x8d, 0x3a, 0x15, 0x86,
	0xf4, 0x51, 0xc8, 0x3a, 0xd3, 0x64, 0x54, 0xa7, 0x2b, 0x32, 0x17, 0xc5, 0x5a, 0xad, 0xac, 0x42,
	0xbc, 0xb8, 0x99, 0x77, 0xc7, 0x4f, 0xb5, 0x52, 0x75, 0x43, 0x99, 0x73, 0xec, 0xba, 0x43, 0x76,
	0xd2, 0x65, 0xdb, 0x92, 0xf6, 0x99, 0xc5, 0x17, 0x84, 0xdc, 0x63, 0xf0, 0x01, 0x66, 0x7b, 0x3a,
	0x8a, 0x8a, 0xa2, 0x20, 0x09, 0xd2, 0x1b, 0xee, 0x27, 0x5c, 0xc3, 0x5d, 0xaf, 0x0a, 0x21, 0x8d,
	0x2d, 0x65, 0x45, 0xd1, 0xbf, 0x24, 0x48, 0xe7, 0xf9, 0x23, 0xeb, 0xe9, 0x6c, 0xa0, 0xb3, 0xb7,
	0x8d, 0xb4, 0xab, 0xfc, 0xbd, 0x6c, 0x3a, 0xe2, 0xb7, 0x7d, 0x68, 0xe3, 0x33, 0x88, 0x30, 0xfd,
	0x10, 0x72, 0x1f, 0x4d, 0x1c, 0xdc, 0xe9, 0xc5, 0x77, 0x00, 0x38, 0xbc, 0xff, 0xd2, 0x34, 0xaa,
	0x2a, 0xad, 0x50, 0x12, 0xb7, 0x70, 0x3f, 0x94, 0x2b, 0x3e, 0xbb, 0x52, 0x5a, 0x61, 0x05, 0x99,
	0x28, 0x48, 0x26, 0xe9, 0x3c, 0x5f, 0xb2, 0xeb, 0x9e, 0xec, 0x1a, 0xc2, 0xd6, 0xd2, 0xea, 0x33,
	0xc7, 0x01, 0xf4, 0x3a, 0x72, 0xe2, 0x2d, 0xfc, 0x77, 0x4b, 0x7c, 0x86, 0x70, 0x58, 0xbb, 0xce,
	0xbf, 0x95, 0xfe, 0x80, 0xf3, 0xd1, 0x8d, 0x31, 0x84, 0xfe, 0x63, 0x67, 0x77, 0x8c, 0x29, 0x1f,
	0xe7, 0xdd, 0xcc, 0x9d, 0x63, 0xf5, 0x13, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x5a, 0x45, 0x70, 0xbe,
	0x01, 0x00, 0x00,
}
